LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := AndroidMigratePrebuilt
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS = APPS
LOCAL_SRC_FILES = $(TARGET_ARCH)/$(LOCAL_MODULE)/$(LOCAL_MODULE)$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH = $(TARGET_OUT_DATA)/../system/priv-app
LOCAL_CERTIFICATE = platform
PRIVILAGED_MODULE = true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := CarrierSetup
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS = APPS
LOCAL_SRC_FILES = $(TARGET_ARCH)/$(LOCAL_MODULE)/$(LOCAL_MODULE)$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH = $(TARGET_OUT_DATA)/../system/priv-app
LOCAL_CERTIFICATE = platform
PRIVILAGED_MODULE = true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ConfigUpdater
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS = APPS
LOCAL_SRC_FILES = $(TARGET_ARCH)/$(LOCAL_MODULE)/$(LOCAL_MODULE)$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH = $(TARGET_OUT_DATA)/../system/priv-app
LOCAL_CERTIFICATE = platform
PRIVILAGED_MODULE = true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GoogleBackupTransport
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS = APPS
LOCAL_SRC_FILES = $(TARGET_ARCH)/$(LOCAL_MODULE)/$(LOCAL_MODULE)$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH = $(TARGET_OUT_DATA)/../system/priv-app
LOCAL_CERTIFICATE = platform
PRIVILAGED_MODULE = true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GoogleExtServices
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS = APPS
LOCAL_SRC_FILES = $(TARGET_ARCH)/$(LOCAL_MODULE)/$(LOCAL_MODULE)$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH = $(TARGET_OUT_DATA)/../system/priv-app
LOCAL_CERTIFICATE = platform
PRIVILAGED_MODULE = true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GoogleFeedback
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS = APPS
LOCAL_SRC_FILES = $(TARGET_ARCH)/$(LOCAL_MODULE)/$(LOCAL_MODULE)$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH = $(TARGET_OUT_DATA)/../system/priv-app
LOCAL_CERTIFICATE = platform
PRIVILAGED_MODULE = true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GoogleOneTimeInitializer
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS = APPS
LOCAL_SRC_FILES = $(TARGET_ARCH)/$(LOCAL_MODULE)/$(LOCAL_MODULE)$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH = $(TARGET_OUT_DATA)/../system/priv-app
LOCAL_CERTIFICATE = platform
PRIVILAGED_MODULE = true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GooglePartnerSetup
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS = APPS
LOCAL_SRC_FILES = $(TARGET_ARCH)/$(LOCAL_MODULE)/$(LOCAL_MODULE)$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH = $(TARGET_OUT_DATA)/../system/priv-app
LOCAL_CERTIFICATE = platform
PRIVILAGED_MODULE = true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GoogleRestore
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS = APPS
LOCAL_SRC_FILES = $(TARGET_ARCH)/$(LOCAL_MODULE)/$(LOCAL_MODULE)$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH = $(TARGET_OUT_DATA)/../system/priv-app
LOCAL_CERTIFICATE = platform
PRIVILAGED_MODULE = true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := GoogleServicesFramework
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_CLASS = APPS
LOCAL_SRC_FILES = $(TARGET_ARCH)/$(LOCAL_MODULE)/$(LOCAL_MODULE)$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH = $(TARGET_OUT_DATA)/../system/priv-app
LOCAL_CERTIFICATE = platform
PRIVILAGED_MODULE = true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := Phonesky
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS = APPS
LOCAL_SRC_FILES = $(TARGET_ARCH)/$(LOCAL_MODULE)/$(LOCAL_MODULE)$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH = $(TARGET_OUT_DATA)/../system/priv-app
LOCAL_CERTIFICATE = platform
PRIVILAGED_MODULE = true
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := PrebuiltGmsCore
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS = APPS
LOCAL_SRC_FILES = $(TARGET_ARCH)/$(LOCAL_MODULE)/$(LOCAL_MODULE)$(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH = $(TARGET_OUT_DATA)/../system/priv-app
LOCAL_CERTIFICATE = platform
PRIVILAGED_MODULE = true
include $(BUILD_PREBUILT)

